In [80]:
import numpy as np

### The Basics

In [12]:
#Creating 1D numpy array 
a = np.array([1,2,3,4,5])

print(a)

[1 2 3 4 5]
int32


In [20]:
#Creating 3D numpy array 
b = np.array([[9,8,7],[6,5,4]],dtype=np.float32)
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [21]:
#Creating 3D numpy array 
c = np.array([[[1,2,3,4,5],
                    [6,7,8,9,10],
                    [11,12,13,14,15]],
                    [[16,17,18,19,20],
                    [6,7,8,9,10],
                    [11,12,13,14,15]]],dtype=np.int32)

print(c)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


In [22]:
# ndim: The number of dimensions of the array.

# shape: A tuple of integers indicating the size of the array in each dimension. 

# size: The total number of elements in the array. It is equal to the product of the elements of the shape tuple.

# itemsize: The size of each element in the array in bytes. 

# nbytes: The total number of bytes consumed by the elements of the array. It is calculated as itemsize times the size of the array. It represents the total memory consumption of the array's data.

print("Array a : Dtype = " + str(a.dtype) + " , Dimension = " + str(a.ndim) + " , Shape = " + str(a.shape) + " , Number of Element = " + str(a.size) + " , Item Size = " + str(a.itemsize) + " , Bytes = " + str(a.nbytes))
print("Array b : Dtype = " + str(b.dtype) + " , Dimension = " + str(b.ndim) + " , Shape = " + str(b.shape) + " , Number of Element = " + str(b.size) + " , Item Size = " + str(b.itemsize) + " , Bytes = " + str(b.nbytes))
print("Array c : Dtype = " + str(c.dtype) + " , Dimension = " + str(c.ndim) + " , Shape = " + str(c.shape) + " , Number of Element = " + str(c.size) + " , Item Size = " + str(c.itemsize) + " , Bytes = " + str(c.nbytes))


Array a : Dtype = int32 , Dimension = 2 , Shape = (2, 3) , Number of Element = 6 , Item Size = 4 , Bytes = 24
Array b : Dtype = float32 , Dimension = 2 , Shape = (2, 3) , Number of Element = 6 , Item Size = 4 , Bytes = 24
Array c : Dtype = int32 , Dimension = 3 , Shape = (2, 3, 5) , Number of Element = 30 , Item Size = 4 , Bytes = 120


#### Arange

In [122]:
# Creating a 1D array with values from 0 to 5
x = np.arange(6)
print(x)

# Creating a 2x5 array with values from 0 to 9
x = np.arange(10).reshape(2,5)
print(x)

# Creating a 3x3 array with values from 1 to 9
x = np.arange(1, 11).reshape(2,5)
print(x)

# Creating a 2x4 array with values from 0 to 7 with a step of 2
x = np.arange(0, 8, 2).reshape(2,2)
print(x)

# Creating a 3x3 array with values from 10 to 1 (decreasing order)
x = np.arange(10, 1, -1).reshape(3, 3)
print(x)


[0 1 2 3 4 5]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[0 2]
 [4 6]]
[[10  9  8]
 [ 7  6  5]
 [ 4  3  2]]


#### Identity matrix

In [123]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### Repeat an array

In [129]:
# Creating a NumPy array 'a' with shape (1, 3)
a = np.array([[1, 2, 3]])

# Repeating array 'a' along axis 0, resulting in an array 'b' with shape (3, 3)
b = np.repeat(a, 3, axis=0)
print(b)  

# Repeating array 'a' along axis 1, resulting in an array 'c' with shape (1, 9)
c = np.repeat(a, 3, axis=1)
print(c)  

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 2 2 2 3 3 3]]


### Accessing/Changing Specific Elements, Rows, Columns, etc (slicing)

In [112]:
# Creating a NumPy array 'a' with 2 rows and 5 columns
a = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10]])

# Accessing and printing the element at row 1, column 3 (indexing starts from 0)
print(a[1, 3])

# Accessing and printing the entire first row of the array
print(a[0, :])

# Accessing and printing the entire fifth column of the array
print(a[:, 4])

# Modifying the element at row 1, column 3 to 5
a[1, 3] = 5

# Modifying the entire fifth column to 99
a[:, 4] = 99

# Printing the modified element at row 1, column 3
print(a[1, 3])

# Printing the modified entire first row of the array
print(a[0, :])

# Printing the modified entire fifth column of the array
print(a[:, 4])


9
[1 2 3 4 5]
[ 5 10]
5
[ 1  2  3  4 99]
[99 99]


### Filling Array

In [30]:
# Creating a 5x5 array filled with the value 5
a = np.full(shape=(5, 5), fill_value=5)

# Creating a 5x5 array filled with zeros and specifying the data type as int32
b = np.zeros(shape=(5, 5), dtype=np.int32)

# Creating a 5x5 array filled with ones (data type will be float by default)
c = np.ones(shape=(5, 5))

# Creating a 5x5 array with uninitialized values (the values will be whatever happens to already exist at that memory location)
d = np.empty(shape=(5, 5))

# Creating an array with values from 0 to 100, incrementing by 5
e = np.arange(0, 105, 5)


In [31]:
print("Array 'a':")
print(a)
print("\nArray 'b':")
print(b)
print("\nArray 'c':")
print(c)
print("\nArray 'd':")
print(d)
print("\nArray 'e':")
print(e)

Array 'a':
[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]

Array 'b':
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

Array 'c':
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

Array 'd':
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

Array 'e':
[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100]


### Mathematical Operations

In [39]:
# Defining lists l1 and l2
l1 = [1, 2, 3, 4, 5]
l2 = [6, 7, 8, 9, 10]

# Creating NumPy arrays a1 and a2 from l1 and l2 
a1 = np.array(l1)
a2 = np.array(l2)

print(l1*3)
print(a1*3)

print(l1+l2)
print(a1+a2)

# print(l1*l2) Invalid operation
print(a1*a2)

# print(l1/l2) Invalid operation
print(a1/a2)

# print(l1-l2) Invalid operation
print(a1-a2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 3  6  9 12 15]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 7  9 11 13 15]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[-5 -5 -5 -5 -5]


##### Mathematical functions

In [43]:
# Creating a NumPy array 'a'
a = np.array([2, 5, 9, 16, 25])

# Computing the square root of each element in array 'a'
print(np.sqrt(a))

# Computing the sine of each element in array 'a'
print(np.sin(a))

# Computing the cosine of each element in array 'a'
print(np.cos(a))

# Computing the natural logarithm of each element in array 'a'
print(np.log(a))

# Computing the exponential of each element in array 'a'
print(np.exp(a))

[1.41421356 2.23606798 3.         4.         5.        ]
[ 0.90929743 -0.95892427  0.41211849 -0.28790332 -0.13235175]
[-0.41614684  0.28366219 -0.91113026 -0.95765948  0.99120281]
[0.69314718 1.60943791 2.19722458 2.77258872 3.21887582]
[7.38905610e+00 1.48413159e+02 8.10308393e+03 8.88611052e+06
 7.20048993e+10]


### Array Methods

In [51]:
# Creating a NumPy array 'a'
a = np.array([1, 2, 3, 4])
print(a)

# Appending element 6 to the end of array 'a'
a = np.append(a, 6)
print(a)

# Appending elements 7 and 8 to the end of array 'a'
a = np.append(a, [7, 8])
print(a)

# Inserting element 5 at index 4 in array 'a'
a = np.insert(a, 4, 5)
print(a)


[1 2 3 4]
[1 2 3 4 6]
[1 2 3 4 6 7 8]
[1 2 3 4 5 6 7 8]


#### Delete method

In [59]:
# Creating a NumPy array 'a' with 2 rows and 3 columns
a = np.array([[1, 2, 3],
              [4, 5, 6]])

# Deleting the second element (1D view of array 'a')
print(np.delete(a, 1))

# Deleting the fourth element (1D view of array 'a')
print(np.delete(a, 3))

# Deleting the fifth element (1D view of array 'a')
print(np.delete(a, 4))

# Deleting the first row of array 'a'
print(np.delete(a, 0, 0))

# Deleting the second row of array 'a'
print(np.delete(a, 1, 0))

# Deleting the first column of array 'a'
print(np.delete(a, 0, 1))

# Deleting the second column of array 'a'
print(np.delete(a, 1, 1))

[1 3 4 5 6]
[1 2 3 5 6]
[1 2 3 4 6]
[[4 5 6]]
[[1 2 3]]
[[2 3]
 [5 6]]
[[1 3]
 [4 6]]


### Structuring Methods

In [136]:
# Creating a NumPy array 'a' with shape (5, 4) containing numbers from 1 to 20
a = np.arange(1, 21).reshape(5, 4)
print(a)  # Printing the original array

# Reshaping 'a' to shape (4, 5)
print(a.reshape(4, 5))  

# Reshaping 'a' to a 1D array with shape (20,)
print(a.reshape(20,)) 

# Reshaping 'a' to a column vector with shape (20, 1)
print(a.reshape(20, 1))  

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]]


### Concatenating, Stacking

In [67]:
# Creating NumPy arrays 'a' and 'b' with 2 rows and 3 columns each
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([[7, 8, 9],
              [10, 11, 12]])

# Concatenating arrays 'a' and 'b' along axis 0 (vertically stacking)
c = np.concatenate((a, b), axis=0)
print(c)

# Concatenating arrays 'a' and 'b' along axis 1 (horizontally stacking)
d = np.concatenate((a, b), axis=1)
print(d)

# Stacking arrays 'a' and 'b' along a new axis (axis 0 by default)
e = np.stack((a, b))
print(e)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


#### Splitting

In [78]:
# Creating a NumPy array 'x' with 6 rows and 4 columns
x = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11],
              [12, 13, 14, 15],
              [16, 17, 18, 19],
              [20, 21, 22, 23]])

# Splitting array 'x' into 2 equal parts along axis 0
print(np.split(x, 2, axis=0))

# Splitting array 'x' into 2 equal parts along axis 1
print(np.split(x, 2, axis=1))

[array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17],
       [20, 21]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])]


### Aggregate Functions

In [76]:
# Creating a NumPy array 'x' with 6 rows and 4 columns
x = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11],
              [12, 13, 14, 15],
              [16, 17, 18, 19],
              [20, 21, 22, 23]])

# Finding the maximum value in array 'x'
print("Maximum value in the array:", x.max())

# Finding the minimum value in array 'x'
print("Minimum value in the array:", x.min())

# Finding the sum of all elements in array 'x'
print("Sum of all elements in the array:", x.sum())

# Finding the mean (average) of all elements in array 'x'
print("Mean (average) of all elements in the array:", x.mean())

Maximum value in the array: 23
Minimum value in the array: 0
Sum of all elements in the array: 276
Mean (average) of all elements in the array: 11.5


### NumPy Random

In [111]:
# Generating a NumPy array of random integers with values ranging from 0 to 99,
# and with a shape of 2 rows and 5 columns
numbers = np.random.randint(100, size=(2, 5))
print(numbers)

# Generating a NumPy array of random integers with values ranging from 10 to 19,
# and with a shape of 2 rows and 5 columns
numbers = np.random.randint(10, 20, size=(2, 5))
print(numbers)

# Generating a NumPy array of random choices from the given list,
# and with a shape of 2 rows and 5 columns
numbers = np.random.choice([10, 20, 30, 40, 50], size=(2, 5))
print(numbers)

# Generating a NumPy array of random numbers in the range [0, 1),
# with a shape of 2 rows and 5 columns
numbers = np.random.rand(2, 5)
print(numbers)

[[93 43 46 88 91]
 [29 70 27 62 45]]
[[17 13 16 19 15]
 [13 15 10 12 10]]
[[40 10 10 20 10]
 [10 40 40 50 10]]
[[0.87303252 0.0585809  0.82760964 0.06650081 0.96418032]
 [0.1008299  0.17940518 0.60413975 0.26726236 0.00995943]]


### Exporting

In [101]:
# Creating a NumPy array 'x' with 6 rows and 4 columns
x = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7],
              [8, 9, 10, 11],
              [12, 13, 14, 15],
              [16, 17, 18, 19],
              [20, 21, 22, 23]])

# Saving the NumPy array 'x' to an NPY file
np.save("array.npy", x)

# Saving the NumPy array 'x' to a CSV file with comma as delimiter
np.savetxt("array.csv", x, delimiter=",")

### Importing

In [104]:
# Loading the NumPy array from the NPY file
y = np.load("array.npy")
print("Array loaded from NPY file:")
print(y)

# Loading the NumPy array from the CSV file
z = np.loadtxt("array.csv", delimiter=",")
print("Array loaded from CSV file:")
print(z)


Array loaded from NPY file:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Array loaded from CSV file:
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]
 [16. 17. 18. 19.]
 [20. 21. 22. 23.]]
